import javax.swing.*;
import java.awt.*;

public class MineSweeperGUI extends JFrame {
    private static final String TITLE = "Minesweeper";

    private JPanel mainPanel;

    private Grid grid;
    private JButton restartGameButton;
    private JPanel panel1;
    private JButton[][] buttonGrid;

    //public Difficulty difficulty;

    public MineSweeperGUI(String title) {
        super(title);
        $$$setupUI$$$();

        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setContentPane(panel1);
        this.setVisible(true);
        //this.getContentPane().setSize(1000, 1000);
        //this.pack();

        grid = new Grid(5, 5, 10);
        JButton[][] buttonGrid = grid.getGrid();
        buttonGrid = new JButton[10][10];
        mainPanel.setLayout(new GridLayout(grid.height, grid.width));
        restartGameButton.setVisible(true);
        for (JButton[] row : buttonGrid) {
            for (JButton col : row) {
                col = new JButton("empty");
                //col.setText("empty");
                mainPanel.add(col);
            }
        }

    }

    public static void main(String[] args) {
        JFrame frame = new MineSweeperGUI(TITLE);
    }

    private void setRestartGameButton() {
    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        restartGameButton = new JButton();
        restartGameButton.setText("Restart Game");
        panel1.add(restartGameButton, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(mainPanel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    /*public void createGrid(){
        grid = new Grid(difficulty.getWidth(), difficulty.getHeight());
    */
}
